
"""
Response handling utilities for Ask Document AI.

This module extracts, cleans, and formats responses generated
by the language model and optionally attaches document sources.
"""

from typing import Any

from langchain_core.documents import Document


# ============================================================
# Response Extraction
# ============================================================

def extract_response_content(response: Any) -> str:
    """
    Extract text content from a LangChain LLM response.

    Supports both plain string responses and structured
    response content returned by some models.

    Args:
        response:
            LLM response object.

    Returns:
        Extracted response text.
    """

    if response is None:
        return ""

    content = getattr(
        response,
        "content",
        response,
    )

    # Standard string response
    if isinstance(content, str):
        return content.strip()

    # Structured content response
    if isinstance(content, list):

        text_parts: list[str] = []

        for item in content:

            if isinstance(item, str):
                text_parts.append(item)

            elif isinstance(item, dict):

                text = item.get("text")

                if text:
                    text_parts.append(str(text))

        return "\n".join(text_parts).strip()

    return str(content).strip()


# ============================================================
# Response Cleaning
# ============================================================

def clean_response(response: Any) -> str:
    """
    Clean and normalize an LLM-generated response.

    Args:
        response:
            LLM response object.

    Returns:
        Cleaned response text.
    """

    content = extract_response_content(response)

    if not content:
        return (
            "I couldn't generate a response. "
            "Please try asking your question again."
        )

    cleaned_lines: list[str] = []
    previous_blank = False

    for line in content.splitlines():

        line = line.strip()

        if not line:

            if not previous_blank:
                cleaned_lines.append("")

            previous_blank = True
            continue

        cleaned_lines.append(line)
        previous_blank = False

    return "\n".join(cleaned_lines).strip()


# ============================================================
# Source Formatting
# ============================================================

def format_sources(
    documents: list[Document],
) -> str:
    """
    Format source metadata from retrieved documents.

    Page numbers generated by PyPDFLoader are zero-indexed,
    so one is added for user-friendly display.

    Args:
        documents:
            Retrieved LangChain Document objects.

    Returns:
        Formatted source list.
    """

    if not documents:
        return ""

    sources: list[str] = []

    for document in documents:

        metadata = document.metadata or {}

        page = metadata.get("page")

        if page is not None:

            try:
                page_number = int(page) + 1
            except (TypeError, ValueError):
                page_number = None

            if page_number is not None:
                sources.append(
                    f"Page {page_number}"
                )

    # Remove duplicate pages while preserving order
    unique_sources = list(
        dict.fromkeys(sources)
    )

    if not unique_sources:
        return ""

    return "\n".join(
        f"- {source}"
        for source in unique_sources
    )


# ============================================================
# Final Response
# ============================================================

def build_final_response(
    response: Any,
    documents: list[Document] | None = None,
) -> str:
    """
    Build the final user-facing chatbot response.

    Args:
        response:
            Raw LLM response.

        documents:
            Retrieved source documents.

    Returns:
        Clean answer with optional source information.
    """

    answer = clean_response(response)

    if not documents:
        return answer

    sources = format_sources(documents)

    if not sources:
        return answer

    return (
        f"{answer}\n\n"
        f"**Sources:**\n"
        f"{sources}"
    )
